# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Category::create(id: 1, name: "PARTE SUPERIOR")
Category::create(id: 2, name: "PARTE INFERIOR")
Category::create(id: 3, name: "CARDIO")
Category::create(id: 4, name: "ABDOMEN")

Exercise::create(name: "LAGARTIJAS", category_id: 1)
Exercise::create(name: "CURL DE BICEP", category_id: 1)
Exercise::create(name: "CURL MARTILLO", category_id: 1)
Exercise::create(name: "TRICEP DIPS", category_id: 1)
Exercise::create(name: "REMO DE PIE", category_id: 1)
Exercise::create(name: "REVERSE FLY", category_id: 1)
Exercise::create(name: "ELEVACION LATERAL", category_id: 1)
Exercise::create(name: "PRESS DE HOMBRO", category_id: 1)
Exercise::create(name: "CLEAN AND PRESS", category_id: 1)
Exercise::create(name: "PRESS DE PECHO", category_id: 1)
Exercise::create(name: "RENEGADOS KETLEBEN", category_id: 1)
Exercise::create(name: "SUMO CON KETLEBEN", category_id: 1)


Exercise::create(name: "SENTADILLA PULSANTE", category_id: 2)
Exercise::create(name: "SENTADILLA BAILARINA", category_id: 2)
Exercise::create(name: "SENTADILLA DE PARED", category_id: 2)
Exercise::create(name: "DESPLANTE EN REVERSA", category_id: 2)
Exercise::create(name: "DESPLANTE CAMINANDO", category_id: 2)
Exercise::create(name: "PESO MUERTO", category_id: 2)
Exercise::create(name: "KETLEBELL SWINGS", category_id: 2)
Exercise::create(name: "PATADA DE MULA", category_id: 2)
Exercise::create(name: "SENTADILLA 1 PIERNA", category_id: 2)
Exercise::create(name: "PATADAS ATRAS", category_id: 2)
Exercise::create(name: "SALTOS DE TRONCO", category_id: 2)

Exercise::create(name: "BURPEES", category_id: 3)
Exercise::create(name: "ESCALADORES", category_id: 3)
Exercise::create(name: "JUMPING JACKS", category_id: 3)
Exercise::create(name: "PATADAS FRONTALES", category_id: 3)
Exercise::create(name: "PLANCHAS JACKS", category_id: 3)
Exercise::create(name: "TROTE RODILLAS ALTAS", category_id: 3)
Exercise::create(name: "DESPLANTE LATERAL", category_id: 3)
Exercise::create(name: "DESPLANTE CON SALTO", category_id: 3)
Exercise::create(name: "DESPLANTE PATINADO", category_id: 3)
Exercise::create(name: "RANAS", category_id: 3)
Exercise::create(name: "SALTO PLEGADO", category_id: 3)

Exercise::create(name: "PLANCHA", category_id: 4)
Exercise::create(name: "PLANCHA CAMINANDO", category_id: 4)
Exercise::create(name: "PLANCHA LATERAL", category_id: 4)
Exercise::create(name: "ABS CRUNCH", category_id: 4)
Exercise::create(name: "ABS INVERSA", category_id: 4)
Exercise::create(name: "GIROS RUSOS", category_id: 4)
Exercise::create(name: "ABS EN V", category_id: 4)
Exercise::create(name: "ABS BICI", category_id: 4)
Exercise::create(name: "ABS PIERNA", category_id: 4)
Exercise::create(name: "SUPERMAN", category_id: 4)

Discipline::create(name: 'PESAS')
Discipline::create(name: 'CROSSFIT')
Discipline::create(name: 'BOOTCAMP')
Discipline::create(name: 'SPINNING')